### ISSUE TITLE
按你这个配置 启动抱错

### ISSUE THREAD

**Issue by devpage** [xujijun/my-spring-boot#1]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userMapper' defined in file [D:\code_repository\spring-boot-starter\springboot-demo-mvc\target\classes\com\springboot\mapper\UserMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory': No qualifying bean of type [org.apache.ibatis.session.SqlSessionFactory] is defined: expected single matching bean but found 2: sqlSessionFactory1,sqlSessionFactory2; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.apache.ibatis.session.SqlSessionFactory] is defined: expected single matching bean but found 2: sqlSessionFactory1,sqlSessionFactory2

**Comment by xujijun** [comment]
根据报错提示应该是两个bean引用了通一个mapper了： sqlSessionFactory1,sqlSessionFactory2 -》UserMapper






At 2016-07-27 01:39:43, "devpage" <notifications@github.com> wrote:


org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userService': Injection of resource dependencies failed; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userMapper' defined in file [D:\code_repository\spring-boot-starter\springboot-demo-mvc\target\classes\com\springboot\mapper\UserMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory': No qualifying bean of type [org.apache.ibatis.session.SqlSessionFactory] is defined: expected single matching bean but found 2: sqlSessionFactory1,sqlSessionFactory2; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.apache.ibatis.session.SqlSessionFactory] is defined: expected single matching bean but found 2: sqlSessionFactory1,sqlSessionFactory2
at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:311) ~[spring-context-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1214) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839) ~[spring-context-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538) ~[spring-context-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118) ~[spring-boot-1.3.6.RELEASE.jar:1.3.6.RELEASE]
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:760) ~[spring-boot-1.3.6.RELEASE.jar:1.3.6.RELEASE]
at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:360) [spring-boot-1.3.6.RELEASE.jar:1.3.6.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:306) [spring-boot-1.3.6.RELEASE.jar:1.3.6.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1185) [spring-boot-1.3.6.RELEASE.jar:1.3.6.RELEASE]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1174) [spring-boot-1.3.6.RELEASE.jar:1.3.6.RELEASE]
at com.springboot.Application.main(Application.java:25) [classes/:?]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userMapper' defined in file [D:\code_repository\spring-boot-starter\springboot-demo-mvc\target\classes\com\springboot\mapper\UserMapper.class]: Unsatisfied dependency expressed through bean property 'sqlSessionFactory': No qualifying bean of type [org.apache.ibatis.session.SqlSessionFactory] is defined: expected single matching bean but found 2: sqlSessionFactory1,sqlSessionFactory2; nested exception is org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.apache.ibatis.session.SqlSessionFactory] is defined: expected single matching bean but found 2: sqlSessionFactory1,sqlSessionFactory2
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1307) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1199) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:512) ~[spring-context-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:486) ~[spring-context-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:615) ~[spring-context-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:169) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:308) ~[spring-context-4.2.7.RELEASE.jar:4.2.7.RELEASE]
... 17 more
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type [org.apache.ibatis.session.SqlSessionFactory] is defined: expected single matching bean but found 2: sqlSessionFactory1,sqlSessionFactory2
at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1126) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1014) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1292) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1199) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:543) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.autowireResource(CommonAnnotationBeanPostProcessor.java:512) ~[spring-context-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.getResource(CommonAnnotationBeanPostProcessor.java:486) ~[spring-context-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor$ResourceElement.getResourceToInject(CommonAnnotationBeanPostProcessor.java:615) ~[spring-context-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.annotation.InjectionMetadata$InjectedElement.inject(InjectionMetadata.java:169) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.2.7.RELEASE.jar:4.2.7.RELEASE]
at org.springframework.context.annotation.CommonAnnotationBeanPostProcessor.postProcessPropertyValues(CommonAnnotationBeanPostProcessor.java:308) ~[spring-context-4.2.7.RELEASE.jar:4.2.7.RELEASE]
... 17 more
2016-07-26 13:47:41,404:INFO main (ClasspathLoggingApplicationListener.java:57) - Application failed to start with classpath: [file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/charsets.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/deploy.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/ext/access-bridge-64.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/ext/dnsns.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/ext/jaccess.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/ext/localedata.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/ext/sunec.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/ext/sunjce_provider.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/ext/sunmscapi.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/ext/zipfs.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/javaws.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/jce.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/jfr.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/jfxrt.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/jsse.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/management-agent.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/plugin.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/resources.jar, file:/D:/soft_dev/Java/jdk1.7.0_79/jre/lib/rt.jar, file:/D:/code_repository/spring-boot-starter/springboot-demo-mvc/target/classes/, file:/D:/jar_repository/maven/org/springframework/boot/spring-boot-configuration-processor/1.3.6.RELEASE/spring-boot-configuration-processor-1.3.6.RELEASE.jar, file:/D:/jar_repository/maven/org/json/json/20140107/json-20140107.jar, file:/D:/jar_repository/maven/org/springframework/spring-core/4.2.7.RELEASE/spring-core-4.2.7.RELEASE.jar, file:/D:/jar_repository/maven/org/springframework/boot/spring-boot-starter-web/1.3.6.RELEASE/spring-boot-starter-web-1.3.6.RELEASE.jar, file:/D:/jar_repository/maven/org/springframework/boot/spring-boot-starter-tomcat/1.3.6.RELEASE/spring-boot-starter-tomcat-1.3.6.RELEASE.jar, file:/D:/jar_repository/maven/org/apache/tomcat/embed/tomcat-embed-core/8.0.36/tomcat-embed-core-8.0.36.jar, file:/D:/jar_repository/maven/org/apache/tomcat/embed/tomcat-embed-el/8.0.36/tomcat-embed-el-8.0.36.jar, file:/D:/jar_repository/maven/org/apache/tomcat/embed/tomcat-embed-logging-juli/8.0.36/tomcat-embed-logging-juli-8.0.36.jar, file:/D:/jar_repository/maven/org/apache/tomcat/embed/tomcat-embed-websocket/8.0.36/tomcat-embed-websocket-8.0.36.jar, file:/D:/jar_repository/maven/org/springframework/boot/spring-boot-starter-validation/1.3.6.RELEASE/spring-boot-starter-validation-1.3.6.RELEASE.jar, file:/D:/jar_repository/maven/org/hibernate/hibernate-validator/5.2.4.Final/hibernate-validator-5.2.4.Final.jar, file:/D:/jar_repository/maven/javax/validation/validation-api/1.1.0.Final/validation-api-1.1.0.Final.jar, file:/D:/jar_repository/maven/org/jboss/logging/jboss-logging/3.3.0.Final/jboss-logging-3.3.0.Final.jar, file:/D:/jar_repository/maven/com/fasterxml/jackson/core/jackson-databind/2.6.7/jackson-databind-2.6.7.jar, file:/D:/jar_repository/maven/com/fasterxml/jackson/core/jackson-annotations/2.6.7/jackson-annotations-2.6.7.jar, file:/D:/jar_repository/maven/org/springframework/spring-web/4.2.7.RELEASE/spring-web-4.2.7.RELEASE.jar, file:/D:/jar_repository/maven/org/springframework/spring-aop/4.2.7.RELEASE/spring-aop-4.2.7.RELEASE.jar, file:/D:/jar_repository/maven/aopalliance/aopalliance/1.0/aopalliance-1.0.jar, file:/D:/jar_repository/maven/org/springframework/spring-webmvc/4.2.7.RELEASE/spring-webmvc-4.2.7.RELEASE.jar, file:/D:/jar_repository/maven/org/springframework/spring-expression/4.2.7.RELEASE/spring-expression-4.2.7.RELEASE.jar, file:/D:/jar_repository/maven/org/springframework/boot/spring-boot-starter-thymeleaf/1.3.6.RELEASE/spring-boot-starter-thymeleaf-1.3.6.RELEASE.jar, file:/D:/jar_repository/maven/org/thymeleaf/thymeleaf-spring4/2.1.4.RELEASE/thymeleaf-spring4-2.1.4.RELEASE.jar, file:/D:/jar_repository/maven/org/thymeleaf/thymeleaf/2.1.4.RELEASE/thymeleaf-2.1.4.RELEASE.jar, file:/D:/jar_repository/maven/ognl/ognl/3.0.8/ognl-3.0.8.jar, file:/D:/jar_repository/maven/org/javassist/javassist/3.18.1-GA/javassist-3.18.1-GA.jar, file:/D:/jar_repository/maven/org/unbescape/unbescape/1.1.0.RELEASE/unbescape-1.1.0.RELEASE.jar, file:/D:/jar_repository/maven/nz/net/ultraq/thymeleaf/thymeleaf-layout-dialect/1.3.3/thymeleaf-layout-dialect-1.3.3.jar, file:/D:/jar_repository/maven/org/codehaus/groovy/groovy/2.4.7/groovy-2.4.7.jar, file:/D:/jar_repository/maven/org/springframework/boot/spring-boot-starter-freemarker/1.3.6.RELEASE/spring-boot-starter-freemarker-1.3.6.RELEASE.jar, file:/D:/jar_repository/maven/org/freemarker/freemarker/2.3.24-incubating/freemarker-2.3.24-incubating.jar, file:/D:/jar_repository/maven/org/springframework/spring-context-support/4.2.7.RELEASE/spring-context-support-4.2.7.RELEASE.jar, file:/D:/jar_repository/maven/org/springframework/boot/spring-boot-starter-velocity/1.3.6.RELEASE/spring-boot-starter-velocity-1.3.6.RELEASE.jar, file:/D:/jar_repository/maven/commons-beanutils/commons-beanutils/1.9.2/commons-beanutils-1.9.2.jar, file:/D:/jar_repository/maven/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar, file:/D:/jar_repository/maven/commons-digester/commons-digester/2.1/commons-digester-2.1.jar, file:/D:/jar_repository/maven/org/apache/velocity/velocity/1.7/velocity-1.7.jar, file:/D:/jar_repository/maven/commons-lang/commons-lang/2.4/commons-lang-2.4.jar, file:/D:/jar_repository/maven/org/apache/velocity/velocity-tools/2.0/velocity-tools-2.0.jar, file:/D:/jar_repository/maven/commons-chain/commons-chain/1.1/commons-chain-1.1.jar, file:/D:/jar_repository/maven/commons-validator/commons-validator/1.3.1/commons-validator-1.3.1.jar, file:/D:/jar_repository/maven/dom4j/dom4j/1.1/dom4j-1.1.jar, file:/D:/jar_repository/maven/oro/oro/2.0.8/oro-2.0.8.jar, file:/D:/jar_repository/maven/sslext/sslext/1.2-0/sslext-1.2-0.jar, file:/D:/jar_repository/maven/org/apache/struts/struts-core/1.3.8/struts-core-1.3.8.jar, file:/D:/jar_repository/maven/antlr/antlr/2.7.7/antlr-2.7.7.jar, file:/D:/jar_repository/maven/org/apache/struts/struts-taglib/1.3.8/struts-taglib-1.3.8.jar, file:/D:/jar_repository/maven/org/apache/struts/struts-tiles/1.3.8/struts-tiles-1.3.8.jar, file:/D:/jar_repository/maven/org/springframework/boot/spring-boot-starter-mail/1.3.6.RELEASE/spring-boot-starter-mail-1.3.6.RELEASE.jar, file:/D:/jar_repository/maven/org/springframework/spring-context/4.2.7.RELEASE/spring-context-4.2.7.RELEASE.jar, file:/D:/jar_repository/maven/com/sun/mail/javax.mail/1.5.5/javax.mail-1.5.5.jar, file:/D:/jar_repository/maven/javax/activation/activation/1.1/activation-1.1.jar, file:/D:/jar_repository/maven/org/springframework/boot/spring-boot-starter-jdbc/1.3.6.RELEASE/spring-boot-starter-jdbc-1.3.6.RELEASE.jar, file:/D:/jar_repository/maven/org/springframework/spring-jdbc/4.2.7.RELEASE/spring-jdbc-4.2.7.RELEASE.jar, file:/D:/jar_repository/maven/org/springframework/spring-tx/4.2.7.RELEASE/spring-tx-4.2.7.RELEASE.jar, file:/D:/jar_repository/maven/org/springframework/boot/spring-boot-starter-actuator/1.3.6.RELEASE/spring-boot-starter-actuator-1.3.6.RELEASE.jar, file:/D:/jar_repository/maven/org/springframework/boot/spring-boot-actuator/1.3.6.RELEASE/spring-boot-actuator-1.3.6.RELEASE.jar, file:/D:/jar_repository/maven/org/springframework/boot/spring-boot-starter/1.3.6.RELEASE/spring-boot-starter-1.3.6.RELEASE.jar, file:/D:/jar_repository/maven/org/springframework/boot/spring-boot/1.3.6.RELEASE/spring-boot-1.3.6.RELEASE.jar, file:/D:/jar_repository/maven/org/springframework/boot/spring-boot-autoconfigure/1.3.6.RELEASE/spring-boot-autoconfigure-1.3.6.RELEASE.jar, file:/D:/jar_repository/maven/org/yaml/snakeyaml/1.16/snakeyaml-1.16.jar, file:/D:/jar_repository/maven/org/springframework/boot/spring-boot-starter-log4j2/1.3.6.RELEASE/spring-boot-starter-log4j2-1.3.6.RELEASE.jar, file:/D:/jar_repository/maven/org/apache/logging/log4j/log4j-slf4j-impl/2.4.1/log4j-slf4j-impl-2.4.1.jar, file:/D:/jar_repository/maven/org/apache/logging/log4j/log4j-api/2.4.1/log4j-api-2.4.1.jar, file:/D:/jar_repository/maven/org/apache/logging/log4j/log4j-core/2.4.1/log4j-core-2.4.1.jar, file:/D:/jar_repository/maven/org/slf4j/jcl-over-slf4j/1.7.21/jcl-over-slf4j-1.7.21.jar, file:/D:/jar_repository/maven/org/slf4j/jul-to-slf4j/1.7.21/jul-to-slf4j-1.7.21.jar, file:/D:/jar_repository/maven/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.6.7/jackson-dataformat-yaml-2.6.7.jar, file:/D:/jar_repository/maven/com/fasterxml/jackson/core/jackson-core/2.6.7/jackson-core-2.6.7.jar, file:/D:/jar_repository/maven/org/springframework/data/spring-data-commons/1.11.4.RELEASE/spring-data-commons-1.11.4.RELEASE.jar, file:/D:/jar_repository/maven/org/springframework/spring-beans/4.2.7.RELEASE/spring-beans-4.2.7.RELEASE.jar, file:/D:/jar_repository/maven/org/slf4j/slf4j-api/1.7.21/slf4j-api-1.7.21.jar, file:/D:/jar_repository/maven/org/mybatis/mybatis/3.4.0/mybatis-3.4.0.jar, file:/D:/jar_repository/maven/org/mybatis/mybatis-spring/1.3.0/mybatis-spring-1.3.0.jar, file:/D:/jar_repository/maven/com/zaxxer/HikariCP/2.4.6/HikariCP-2.4.6.jar, file:/D:/jar_repository/maven/mysql/mysql-connector-java/5.1.39/mysql-connector-java-5.1.39.jar, file:/D:/jar_repository/maven/com/github/pagehelper/pagehelper/4.1.6/pagehelper-4.1.6.jar, file:/D:/jar_repository/maven/com/github/jsqlparser/jsqlparser/0.9.5/jsqlparser-0.9.5.jar, file:/D:/jar_repository/maven/com/alibaba/fastjson/1.2.14/fastjson-1.2.14.jar, file:/D:/jar_repository/maven/com/mangofactory/swagger-springmvc/0.9.5/swagger-springmvc-0.9.5.jar, file:/D:/jar_repository/maven/com/wordnik/swagger-annotations/1.3.11/swagger-annotations-1.3.11.jar, file:/D:/jar_repository/maven/com/google/guava/guava/15.0/guava-15.0.jar, file:/D:/jar_repository/maven/com/fasterxml/classmate/1.1.0/classmate-1.1.0.jar, file:/D:/jar_repository/maven/joda-time/joda-time/2.8.2/joda-time-2.8.2.jar, file:/D:/jar_repository/maven/com/mangofactory/swagger-models/0.9.5/swagger-models-0.9.5.jar, file:/D:/jar_repository/maven/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.jar, file:/D:/soft_dev/JetBrains/IntelliJ%20IDEA%2015.0.2/lib/idea_rt.jar]
Disconnected from the target VM, address: '127.0.0.1:58371', transport: 'socket'
